### ISSUE TITLE
Make matching footer for the website

### ISSUE THREAD

**Issue by abhishekmsingh** [opencodeiiita/libook#12]
The footer should consist of name of the organization,name of the app, contact no. and a copy right statement. You can arrange the components however you want just match the theme.

**Comment by pradhuman1** [comment]
can i claim this issue

**Comment by shuba400** [comment]
claim this issue

**Comment by abhishekmsingh** [comment]
sorry @shuba400 the issue goes to @pradhuman1 . All the best
