### ISSUE TITLE
Remove 'your titles will appear here' when the first title is added

### ISSUE THREAD

**Issue by abhishekmsingh** [opencodeiiita/libook#13]
note that in it's current form, when you add the first title the card 'your titles will appear here' is not removed dynamically. However when you reload the page, the card dissapears your task is to do this dynamically. To delete a title you need to clear the local storage (currently).

**Comment by pradhuman1** [comment]
can i claim this issue

**Comment by sanskar-p** [comment]
claim

**Comment by abhishekmsingh** [comment]
Sorry @sanskar-p the issue goes to @pradhuman1

**Comment by abhishekmsingh** [comment]
@pradhuman1  note that in it's current form, when you add the first title the card 'your titles will appear here' is not removed dynamically. However when you reload the page, the card dissapears your task is to do this dynamically. To delete a title you need to clear the local storage (currently).
