### ISSUE TITLE
Make the website responsive

### ISSUE THREAD

**Issue by abhishekmsingh** [opencodeiiita/libook#29]
Go to the mobile view of the website and you can see how the search and add title buttons appear dis-oriented. Fix that. Note that the desktop view should not be affected.

**Comment by blaze-assault** [comment]
Claim

**Comment by abhishekmsingh** [comment]
Go on @blaze-assault

**Comment by griffy06** [comment]
Since there is no one assigned yet, can I claim this?

**Comment by rox999** [comment]
i want to work on this

**Comment by ananya-mohanty** [comment]
Can I work on this?

**Comment by Piyush4064** [comment]
https://github.com/Piyush4064/opencode20-destination-portal.git

**Comment by Piyush4064** [comment]
Can I work on this?

**Comment by abhishekmsingh** [comment]
sorry guys i forgot to assign @blaze-assault. He first claimed so the issue goes to him for the next two days.
