### ISSUE TITLE
Make the search bar filter the titles

### ISSUE THREAD

**Issue by abhishekmsingh** [opencodeiiita/libook#3]
When searched with a query, only those titles should be visible which partially or completely matches the query ignoring the case. Do not redirect or load another page make the changes on the current page only. Please read how the data is getting stored in the local storage in the Readme.

**Comment by griffy06** [comment]
@opencodebot claim

**Comment by sarthakm21** [comment]
claim

**Comment by abhishekmsingh** [comment]
Sorry @sarthakm21  the issue goes to @griffy06 . Since he claimed first.
