### ISSUE TITLE
Add details functionality and change how things are stored

### ISSUE THREAD

**Issue by abhishekmsingh** [opencodeiiita/libook#36]
Add a text field/area which takes details, author, page no for the titles as input. Position them accordingly. You may use the space taken by "Lorem ipsum.....". Change the add titles button to add book. Now change the local storage such that the title is the key and the value is json(as a string of course) consisting of the following fields:
{
"title": title,
"details": details,
"img": img,
"addedAt": date and time of addition, 
"startedAt": date and time of addition,
"finishedAt": date and time of finishing,
"author": Author,
"Pages": no of pages,
}
default value of fields img, startedAt, finishedAt should be "not available" or anything indicative of the same.

**Comment by pradhuman1** [comment]
Can I claim this issue

**Comment by abhishekmsingh** [comment]
ok @pradhuman1

**Comment by ananya-mohanty** [comment]
Can I work on this?

**Comment by pradhuman1** [comment]
Sir do I have to fill all details in localstorage or just title,author and no of pages

**Comment by pradhuman1** [comment]
What is 'details' in in localstorage

**Comment by abhishekmsingh** [comment]
> Can I work on this?

Sorry @ananya-mohanty this issue was claimed by @pradhuman1 first.

**Comment by sggts04** [comment]
Sir can I work on this? Its been 2 days.

**Comment by pradhuman1** [comment]
Sir i done it ,when i run its html file it runs properly but in live link it shows error "Unexpected token k in JSON at position 0"

**Comment by pradhuman1** [comment]
Sir Just provide some more time i will do it.

**Comment by abhishekmsingh** [comment]
Ok keeping in mind the size of issue and the college schedule @pradhuman1 gets more time. Sorry @sggts04 not now. But be quick @pradhuman1
