### ISSUE TITLE
Add field validations for author, summary

### ISSUE THREAD

**Issue by abhishekmsingh** [opencodeiiita/libook#47]
For the purpose of maintaining uniformity, use the same alert types as used in blank title i.e the temporary red border. There is a principle called DRY (Don't Repeat Yourself ) in development or programming in general. Follow this principle and maintain minimum redundancy in code.

**Comment by sggts04** [comment]
claim

**Comment by abhishekmsingh** [comment]
You got it @sggts04

**Comment by pradhuman1** [comment]
Claim
