### ISSUE TITLE
Making the add book form collapsible

### ISSUE THREAD

**Issue by abhishekmsingh** [opencodeiiita/libook#49]
As you can see that the add book form, takes up quite a space and is inconvenient for those who just wanna browse their collection.  We need to make that part collapsible.  That jumbotron container in its collapsed form should have the same heading Add books on the right with maybe some text below it (only if it looks good) and at the right should be the collapse trigger i.e a button maybe a '+' or a down arrow  which on click expands(or collapses) the form. Maintain the overall theme. PR's with sub par styling would not be merged. Styling is an important point of this issue,

**Comment by sggts04** [comment]
claim

**Comment by sarthakm21** [comment]
claim

**Comment by mendelevium28** [comment]
claim

**Comment by abhishekmsingh** [comment]
You got that again @sggts04.

**Comment by pradhuman1** [comment]
Claim
