### ISSUE TITLE
Improving the cards

### ISSUE THREAD

**Issue by abhishekmsingh** [opencodeiiita/libook#50]
Currently the cards show only the title of the book which is not very helpful. Use the bootstrap 4 cards and design them as follows:
1. The card header should be the title.
2. The card body should be the details or summary of the title which is mentioned in the card header of that card.
3. The card footer should be the author's name.
Maintain the theme. Sub par styling wouldn't be accepted.

**Comment by sanskar-p** [comment]
claim

**Comment by abhishekmsingh** [comment]
You got it @sanskar-p

**Comment by pradhuman1** [comment]
Claim

**Comment by abhishekmsingh** [comment]
@sanskar-p updates

**Comment by sanskar-p** [comment]
> @sanskar-p updates

Sir I haven't been able to complete the task as I'm working on it while simultaneously learning Javascript basics.

**Comment by Rohini13** [comment]
Claim

**Comment by abhishekmsingh** [comment]
One day more that's the deadline. Tomorrow 9pm. If it's not done, I may have to think of re-assigning this issue.

**Comment by abhishekmsingh** [comment]
The issue is assigned to @Rohini13

**Comment by abhishekmsingh** [comment]
@Rohini13 are you fine with that.

**Comment by Rohini13** [comment]
@abhiandthetruth  m working on it

**Comment by sarthakm21** [comment]
Claim

**Comment by blaze-assault** [comment]
Claim
