### ISSUE TITLE
Handling Json parsing exception

### ISSUE THREAD

**Issue by abhishekmsingh** [opencodeiiita/libook#51]
Currently if there is a key whose value is not formatted as json, the whole card viewing system breaks and no cards are visible. This is since we do not handle exceptions properly. Handle the exception so that an ill-formatted key value pair is skipped and the exception generated is logged in the console.
To reproduce this add some titles, go to the console, enter the command localStorage.setItem("0", "hello") and reload. You will see no titles are displayed.

**Comment by sggts04** [comment]
claim

**Comment by abhishekmsingh** [comment]
One person is restricted to a maximum of two issues in a repo. So sorry @sggts04 not this time.

**Comment by untrulynoxiusmj** [comment]
claim

**Comment by pradhuman1** [comment]
Claim

**Comment by abhishekmsingh** [comment]
@untrulynoxiusmj you have been assigned this issue
