### ISSUE TITLE
introduce search by option

### ISSUE THREAD

**Issue by abhishekmsingh** [opencodeiiita/libook#57]
Issue assigned to @pradhuman1 since he suggested the feature. Please style properly and use DRY principles. I don't know how it will be implemented its onto you.

**Comment by blaze-assault** [comment]
Claim

**Comment by starboi02** [comment]
Claim

**Comment by blaze-assault** [comment]
@abhiandthetruth please assign issue

**Comment by garvitchittora** [comment]
claim
