### ISSUE TITLE
Add a page book.html and link it with every titles

### ISSUE THREAD

**Issue by abhishekmsingh** [opencodeiiita/libook#61]
On clicking a title, a get request should be send to book.html with query title=[book title]. And make book.html display the title name of which it was clicked.

**Comment by untrulynoxiusmj** [comment]
claim

**Comment by abhishekmsingh** [comment]
Do it @untrulynoxiusmj.

**Comment by garvitchittora** [comment]
claim

**Comment by sarthakm21** [comment]
claim
