### ISSUE TITLE
integrate pdf.js for pdf viewing

### ISSUE THREAD

**Issue by abhishekmsingh** [opencodeiiita/libook#65]
Add a webpage in pages folder integrated with pdf.js for pdf viewing. You can currently hard-code the pdf source to be any pdf file which you willl upload in resources. Make the page theme match that of our website if possible.

**Comment by sggts04** [comment]
claim

**Comment by griffy06** [comment]
claim

**Comment by abhishekmsingh** [comment]
you got it @sggts04
