### ISSUE TITLE
Make Bootstrap available offline

### ISSUE THREAD

**Issue by abhishekmsingh** [opencodeiiita/libook#7]
Just in case somebody doesn't have internet connection, the ui should not go down when locally hosted. To ensure that remove the bootstrap cdn and download the bootstrap __4__ files. Make sure you download the compiled files not source. You must place the css contents in 'styles/bootstrap-css/' and scripts in 'scripts/bootsrap-js/' directly. Link those to index.html. The website should render properly without internet connection.

**Comment by shuba400** [comment]
I am working in this issue
