### ISSUE TITLE
Add pdf upload facility

### ISSUE THREAD

**Issue by abhishekmsingh** [opencodeiiita/libook#72]
Add drag and drop upload panel to the right of the form of adding books where the sample text is written. The pdf should be stored in local storage in string format using base64 encodeing. Maintain the ui in sync with the website.

**Comment by Rohini13** [comment]
Claim

**Comment by abhishekmsingh** [comment]
it's yours @Rohini13

**Comment by pradhuman1** [comment]
claim

**Comment by sggts04** [comment]
can I work on this?

**Comment by abhishekmsingh** [comment]
Rohini give updates regarding this issue. The update should be solid. You
have time until tomorrow. Otherwise the issue will be reassigned.

**Comment by abhishekmsingh** [comment]
@pradhuman1 you have been assigned the issue. Please make it quick. Reply if you are interested.

**Comment by pradhuman1** [comment]
Yes I m interested
