### ISSUE TITLE
Prevent blank titles

### ISSUE THREAD

**Issue by abhishekmsingh** [opencodeiiita/libook#8]
Currently the title can be blank and still get added in the list. Prevent this action, and notify the user that title is empty by making the border of the text box momentarily red. You may add some text also to indicate it.

**Comment by Mukul-M** [comment]
can i work on this issue

**Comment by abhishekmsingh** [comment]
Yes. Go on

**Comment by pradhuman1** [comment]
can i claim this issue

**Comment by abhishekmsingh** [comment]
No @pradhuman1 the issue is already claimed. If the assigned person does'nt complete this in the alloted time you can claim it.

**Comment by abhishekmsingh** [comment]
@Mukul-M any updates

**Comment by pradhuman1** [comment]
Sir can I work on this now

**Comment by abhishekmsingh** [comment]
yes @pradhuman1 it's yours
