### ISSUE TITLE
Prevent Duplicate titles

### ISSUE THREAD

**Issue by abhishekmsingh** [opencodeiiita/libook#9]
If someone enters a duplicate title, you must notify them. Don't use alerts. Just display the message in red below the text box or somewhere it is pleasant

**Comment by ananya-mohanty** [comment]
Can I work on this?

**Comment by abhishekmsingh** [comment]
Go On. All the best.

**Comment by pradhuman1** [comment]
can i claim this issue

**Comment by abhishekmsingh** [comment]
If the issue is not solved in the next day it will go to you @pradhuman1

**Comment by pradhuman1** [comment]
Sir can I work on this now
